excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - iddog/Resources/R.generated.swift
  
disabled_rules:
  - private_over_fileprivate

function_body_length:
  - 20

cyclomatic_complexity:
  - 5

identifier_name:
  excluded: # excluded via string array
    - id
    - URL
